### PR TITLE
Upgrade Ember CLI to 3.5

### PR DESCRIPTION
**Pull request by SergeAstapov**
Resolves deprecation warning
```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.1.7 located: /Users/sastapov/Code/agwa/node_modules/ember-cli-jsdoc/node_modules/ember-cli-babel
```

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@notmessenger @softlayer ping on this request

**Comment by notmessenger** [comment]
@SergeAstapov I haven't been in this mind space for a while.  What semver should this package be published as?  2.1.0 or 3.0.0?

**Comment by SergeAstapov** [comment]
@notmessenger thank you for looking into this! I think it should be major bump as support for "node": ">= 0.12.0" was removed and it Ember CLI 3.5 request at lease Node.js 6

**Comment by SergeAstapov** [comment]
Hi @notmessenger! Do you have bandwidth to release new version?

**Comment by notmessenger** [comment]
@SergeAstapov https://github.com/softlayer/ember-cli-jsdoc/releases/tag/v3.0.0 has been released

**Comment by SergeAstapov** [comment]
Thank you @notmessenger!

**Pull request merged**
