### PR TITLE
Closes softlayer/ember-cli-jsdoc#16

### PR DESCRIPTION
**Pull request by SpikedKira**
This change is [Review on Reviewable](https://reviewable.io/reviews/softlayer/ember-cli-jsdoc/20)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/ember-cli-jsdoc/20)_

**Comment by notmessenger** [comment]
```
Cannot find module 'process'
Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Class.module.exports.run (/Users/jeremy/Desktop/throwAway/sl-ember-components/node_modules/ember-cli-jsdoc/lib/commands/ember-cli-jsdoc.js:10:19)
    at Class.<anonymous> (/Users/jeremy/Desktop/throwAway/sl-ember-components/node_modules/ember-cli/lib/models/command.js:146:17)
    at lib$rsvp$$internal$$tryCatch (/Users/jeremy/Desktop/throwAway/sl-ember-components/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jeremy/Desktop/throwAway/sl-ember-components/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/jeremy/Desktop/throwAway/sl-ember-components/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/jeremy/Desktop/throwAway/sl-ember-components/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

This was encountered when clone `sl-ember-components`, changing the `ember-cli-jsdoc` entry in _package.json_ to `spikedkira/ember-cli-jsdoc#issue-16`, running "nombom" and then `ember ember-cli-jsdoc`.  Need to add it as a dependency?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/ember-cli-jsdoc/20#-:-KCXmpQ0dCx-MgeqNK7d:1055573694)_

**Comment by SpikedKira** [comment]
Apparently there are differences in node versions and the process global.  I was requiring, looks like my version silently said "okay" while other versions say "that doesn't exist; use process global already included"

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/ember-cli-jsdoc/20#-:-KCa8baJDwqgnG85W3G9:1987707186)_

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/ember-cli-jsdoc/20)_

**Pull request merged**
